<?php
require_once('application/models/main.model.php');
		if(isset($_SESSION['uid']))
		{
			require('application/views/layouts/header.php');
			require('application/views/layouts/sidebar.php');
				if(isset($_GET['addEmployee']))
				{
					require_once('application/views/teller/addEmployee.php');
				}
			require('application/views/layouts/footer.php');
		}
		else
		{
			require('application/views/login.php');
		}
?>